spring:
  application:
    name: techNovaApplication
  profiles:
    active: dev
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org.hibernate: ERROR
